apiVersion: v1
kind: Service
metadata:
  labels:
    type: frontend
  name: documentation
  namespace: learn-kubernetes

spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    type: frontend
  type: NodePort

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: documentation
  labels:
    type: frontend
  namespace: learn-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
      name: documentation
      namespace: learn-kubernetes

    spec:
      containers:
        - name: frontend
          image: learn-kubernetes/documentation:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"