apiVersion: v1
kind: Service
metadata:
  namespace: learn-kubernetes
  name: documentation-svc
spec:
  selector:
    app: documentation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort