apiVersion: v1
kind: Pod

metadata:
  labels:
    type: backend
  name: api
  namespace: learn-kubernetes

spec:
  containers:
    - name: api
      image: learn-kubernetes/api
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: 256Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 500m
      env:
        - name: PORT
          value: "8080"