apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: learn-kubernetes
  name: pdf
  labels:
    app: pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf
  template:
    metadata:
      labels:
        app: pdf
    spec:
      containers:
        - name: main
          image: //services/pdf/k8s:image
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 8080