apiVersion: v1
kind: Pod
metadata:
  labels:
    type: frontend
  namespace: learn-kubernetes
  name: frontend

spec:
  containers:
    - name: frontend
      image: learn-kubernetes/frontend
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: 128Mi
          cpu: 500m
        limits:
          memory: 256Mi
          cpu: 500m