apiVersion: v1
kind: Pod

metadata:
  labels:
    type: backend
  name: api
  namespace: learn-kubernetes

spec:
  containers:
    - name: api
      image: localhost:32000/api
      resources:
        requests:
          memory: 256Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 500m